principles_office/urls.py
"""Imports."""
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import include, path

from reports import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('reports/', include('reports.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('po/<int:po_id>', views.po, name='po'),
    path('create-po/', views.create_po, name='create_po'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,
                                       document_root=settings.MEDIA_ROOT)

reports/urls.py
"""Imports."""
from django.urls import path

from reports import views

app_name = 'reports'
urlpatterns = [
    path('', views.reports_index, name='reports_index'),
    path('<int:report_id>/', views.report, name='report'),
    path('add_officer/<int:report_id>', views.add_officer, name='add_officer'),
    path('make_report/', views.make_report, name='make_report'),
]

reports/models.py
"""Imports."""
from django.contrib.auth.models import User
from django.db import models


class PrinciplesOffice(models.Model):
    """Define a principles office."""

    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        """Give the model a label in admin."""
        return self.name


class UserProfile(models.Model):
    """Define a User."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    po = models.ForeignKey(PrinciplesOffice, on_delete=models.CASCADE, null=True, blank=True)
    burner_name = models.CharField(max_length=50)
    picture = models.ImageField(upload_to='user_pics/%Y/%m/%d/')
    about = models.TextField()
    fun_fact = models.CharField(max_length=200)
    email = models.EmailField(max_length=254)
    cell_phone = models.CharField(max_length=15, blank=True)
    show_email = models.BooleanField(default=False)
    show_phone = models.BooleanField(default=False)

    def __str__(self):
        """Give the model a label in admin."""
        return str(self.user)


class Report(models.Model):
    """Define a report."""

    title = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)
    updated = models.DateTimeField(auto_now=True)
    po = models.ForeignKey(PrinciplesOffice, on_delete=models.PROTECT,
                           related_name='reports')
    synopsis = models.TextField()
    active = models.BooleanField(default=True)

    def __str__(self):
        """Give the model a label in admin."""
        return self.title + '/' + str(self.po) + '/' + str(self.created)


class ReportAccused(models.Model):
    """Connect accused to a report."""

    report = models.ForeignKey(Report, on_delete=models.CASCADE, related_name='accused')
    first_name = models.CharField(max_length=50)
    alt_first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50)
    alt_last_name = models.CharField(max_length=50, blank=True)
    burner_name = models.CharField(max_length=50)
    alt_burner_name = models.CharField(max_length=50, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    statement = models.TextField(blank=True)

    def __str__(self):
        """Give the model a label in admin."""
        return (str(self.report) + '/' + self.last_name + ', ' + self.first_name)


class ReportAccuser(models.Model):
    """Connect accuser to a report."""

    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    alt_first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50)
    alt_last_name = models.CharField(max_length=50, blank=True)
    burner_name = models.CharField(max_length=50)
    alt_burner_name = models.CharField(max_length=50, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    statement = models.TextField(blank=True)

    def __str__(self):
        """Give the model a label in admin."""
        return (str(self.report) + '/' + self.last_name + ', ' + self.first_name)


class ReportWitness(models.Model):
    """Connect witness to a report."""

    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    alt_first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50)
    alt_last_name = models.CharField(max_length=50, blank=True)
    burner_name = models.CharField(max_length=50)
    alt_burner_name = models.CharField(max_length=50, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    statement = models.TextField(blank=True)

    def __str__(self):
        """Give the model a label in admin."""
        return (str(self.report) + '/' + self.last_name + ', ' + self.first_name)


class ReportOfficer(models.Model):
    """Connect officers to a report."""

    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    officer = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    statement = models.TextField(blank=True)
    lead = models.BooleanField(default=False)

    def __str__(self):
        """Give the model a label in admin."""
        return str(self.report) + '/' + str(self.officer)


class ReportImage(models.Model):
    """Connect image to a report."""

    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='report_image/%Y/%m/%d/')
    name = models.CharField(max_length=250, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    description = models.CharField(max_length=250, blank=True)

    def __str__(self):
        """Give the model a label in admin."""
        return str(self.report) + '/' + str(self.created)


class ReportFile(models.Model):
    """Connect file to a report."""

    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    file = models.FileField(upload_to='report_file/%Y/%m/%d/')
    name = models.CharField(max_length=250, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    description = models.CharField(max_length=250, blank=True)

    def __str__(self):
        """Give the model a label in admin."""
        return str(self.report) + '/' + str(self.created)


class Poll(models.Model):
    """Define a poll."""

    text = models.CharField(max_length=250)
    report = models.ForeignKey(Report, on_delete=models.CASCADE,
                               related_name='polls')
    creator = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        """Give the model a label in admin."""
        return str(self.report) + '/' + self.text


class Response(models.Model):
    """Define a response to a poll."""

    poll = models.ForeignKey(Poll, on_delete=models.CASCADE,
                             related_name='responses')
    text = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Give the model a label in admin."""
        return str(self.poll) + '/' + self.text

reports/forms.py
"""Imports."""
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import PrinciplesOffice
from .models import UserProfile
from .models import ReportOfficer  # WILLOWISSEXYBEAST


def get_choices(option):
    if option == 'get_users':
        # do stuff
        return


class SignUpForm(UserCreationForm):
    """Layout form."""

    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)

    class Meta:
        """Define model."""

        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1',
                  'password2', )


class CreatePOForm(forms.ModelForm):
    """Layout form."""

    class Meta:
        """Define model."""

        model = PrinciplesOffice
        fields = ('name',)


class AddOfficerForm(forms.ModelForm):
    def __init__(self, po_id, *args, **kwargs):
        super().__init__(*args, **kwargs)

        CHOICES = (
            ('', ''),
            ('True', 'True'),
            ('False', 'False'),
        )
        print('here')
        print(po_id)
        po = PrinciplesOffice.objects.get(id=po_id)
        user_profile = UserProfile.objects.filter(po=po)
        USER_CHOICES = [
            ('', ''),
        ]
        for user in user_profile:
            usr = User.objects.get(id=user.id)
            USER_CHOICES.append((usr.first_name + ' ' + usr.last_name,
                                usr.first_name + ' ' + usr.last_name))
        self.fields['officer'] = forms.ChoiceField(choices=USER_CHOICES,
                                                   label='Select an officer to add')
        self.fields['lead'] = forms.ChoiceField(widget=forms.CheckboxInput,
                                                choices=CHOICES,
                                                required=False)

reports/views.py
"""Imports."""
from django.contrib.auth import login, authenticate
# from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import SignUpForm, CreatePOForm, AddOfficerForm
from .models import PrinciplesOffice
from .models import Report
from .models import ReportAccused
from .models import UserProfile
from .models import ReportAccuser
from .models import ReportFile
from .models import ReportImage
from .models import ReportOfficer
from .models import ReportWitness

from . import functions


def index(request):
    """View for the main site index."""
    template = 'reports/index.html'
    if request.user.username == '':
        context = {}
    else:
        context = functions.FetchContext(request)
    return render(request, template, context)


def signup(request):
    """View for signing up."""
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = SignUpForm()
        return render(request, 'registration/signup.html', {'form': form})


@login_required
def dashboard(request):
    """View for po dashboard."""
    if request.method == 'POST':
        return
    else:
        template = 'reports/dashboard.html'
        context = functions.FetchContext(request)
        return render(request, template, context)


@login_required
def create_po(request):
    """View for creating a po."""
    if request.method == 'POST':
        form = CreatePOForm(request.POST)
        if form.is_valid():
            new_po = form.save(commit=False)
            new_po.creator = request.user
            new_po.save()
            return redirect('dashboard')
    else:
        template = 'reports/create_po.html'
        context = functions.FetchContext(request)
        form = CreatePOForm()
        context['form'] = form
        return render(request, template, context)


@login_required
def po(request, po_id):
    """View for a po."""
    if request.method == 'POST':
        template = ''
        context = {}
        return render(request, template, context)
    else:
        template = 'reports/po.html'
        context = functions.FetchContext(request)
        po = PrinciplesOffice.objects.get(id=po_id)
        officers = []
        members = UserProfile.objects.filter(po=po)
        for member in members:
            officers.append(member.user.get_full_name)
        context['po'] = po
        context['officers'] = officers
        return render(request, template, context)


@login_required
def reports_index(request):
    """View for viewing reports."""
    template = ''
    context = functions.FetchContext(request)
    return render(request, template, context)


@login_required
def report(request, report_id):
    """View for viewing indivual reports."""
    template = 'reports/report.html'
    context = functions.FetchContext(request)
    report = Report.objects.get(id=report_id)
    context['report'] = report
    accused = ReportAccused.objects.filter(report=report).order_by('last_name')
    context['accused'] = accused
    accuser = ReportAccuser.objects.filter(report=report).order_by('last_name')
    context['accuser'] = accuser
    witnesses = ReportWitness.objects.filter(report=report).order_by('last_name')
    context['witnesses'] = witnesses
    officers = ReportOfficer.objects.filter(report=report).order_by('officer')
    context['officers'] = officers
    images = ReportImage.objects.filter(report=report)
    context['images'] = images
    files = ReportFile.objects.filter(report=report)
    context['files'] = files
    return render(request, template, context)


@login_required
def add_officer(request, report_id):
    template = 'reports/add_officer.html'
    context = functions.FetchContext(request)
    if request.method == 'POST':
        form = AddOfficerForm(request.POST)
        if form.is_valid():
            new_officer = form.save(commit=False)
            report = Report.objects.get(id=report_id)
            new_officer.report = report
            return redirect('reports:%s' % report_id)
    else:
        report = Report.objects.get(id=report_id)
        context['form'] = AddOfficerForm()
        context['report'] = report
        return render(request, template, context)


@login_required
def make_report(request):
    """View for creating reports."""
    template = ''
    context = functions.FetchContext(request)
    return render(request, template, context)

reports/templates/reports/add_officer.html
{% extends "base.html" %}

{% block title %}Add Officer{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row ml-4"">
        <div class="col-sm">
            <div class="card mb-3">
                <div class="card-body">
                    <h1 class="card-title text-center">
                        Add Officer to Report: {{ report.title }}
                    </h1> <!-- card-title -->
                    <div class="card-text text-center">
                        <form method="post">
                            {% csrf_token %}
                            <div class="card-text text-center">
                                {{ form.as_p }}
                                <button class="btn bg-dark mt-2 mb-2 text-white" type="submit">Add Officer</button>
                            </div>
                        </form>
                    </div> <!-- card-text -->
                </div> <!-- card-body -->
            </div> <!-- card -->
        </div> <!-- col-sm -->
    </div> <!-- row -->
</div> <!-- container-fluid -->






<!--
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm">
                <div class="<div class="card">
                    <div class="card-body bg-dark mt-3">
                        <h4 class="card-title text-center text-white bg-info">Add an Officer to {{ report.title }}</h4>
                            <form method="post">
                                {% csrf_token %}
                                <div class="card-text text-center text-white bg-light">
                                    {{ form.as_p }}
                                    <button class="btn bg-info text-white mb-2" type="submit">Add Officer</button>
                                </div>
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
{% endblock %}

reports/templates/reports/add_user.html
{% extends "base.html" %}

{% block title %}Add User{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm">
                <div class="<div class="card">
                    <div class="card-body bg-dark mt-3">
                        <h4 class="card-title text-center text-white bg-info">Add a User to {{ po.name }}</h4>
                            <form method="post">
                                {% csrf_token %}
                                <div class="card-text text-center text-white bg-light">
                                    {{ form.as_p }}
                                    <button class="btn bg-info text-white mb-2" type="submit">Add User</button>
                                </div>
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

reports/templates/reports/create_po.html
{% extends "base.html" %}

{% block title %}Create PO{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm">
                <div class="<div class="card">
                    <div class="card-body bg-dark mt-3">
                        <h4 class="card-title text-center text-white bg-info">Create A New Principles Office</h4>
                        <div class="card-text text-center text-white bg-light">
                            <form method="post">
                                {% csrf_token %}
                                <div class="text-dark">
                                    {{ form.as_p }}
                                </div>
                                <button class="btn bg-info text-white mb-2" type="submit">Create</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

reports/templates/reports/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm mt-3">
            </div>
            <div class="col-sm mt-3">
                <div class="card" style="width:36rem;">
                    <div class="card-body">
                        <h1 class="card-title text-center">Dashboard</h1>
                        <div class="card-text text-center">
                            <p>{{ user.get_short_name }}, Here's what is going on in <a href="{% url 'po' po.id %}" class="btn btn-dark mt-2 mb-2" role='button'>{{ po.name }}</a></p>
                        </div> <!-- card-text -->
                    </div> <!-- card-body -->
                </div> <!-- card -->
            </div> <!-- col-sm -->
            <div class="col-sm mt-3">
            </div>
        </div> <!-- row -->
        <hr />
        <div class="row">
            <div class="col-sm">
                <h4 class="text-center">Active Reports</h4>
                    <div class="card-deck">
                        {% for report in active_reports %}
                            {% if forloop.counter|divisibleby:"4"  %}
                                </div> <!-- card-deck -->
                                <div class="card-deck">
                                    <div class="card" style="width: 16rem;">
                                        <div class="card-body text-center">
                                            <a href="{% url 'reports:report' report.id %}" class="btn btn-dark mt-2 mb-2" role='button'>Report #{{ report.id }}</a>
                                            <p class="card-subtitle mb-2 text-muted">{{ report.title }}</p>
                                            <div class="card-text text-center">
                                                <p>{{ report.synopsis }}</p>
                                            </div> <!-- card-text -->
                                        </div> <!-- card-body -->
                                    </div> <!-- card -->
                                {% else %}
                                    <div class="card" style="width: 16rem;">
                                        <div class="card-body text-center">
                                            <a href="{% url 'reports:report' report.id %}" class="btn btn-dark mt-2 mb-2" role='button'>Report #{{ report.id }}</a>
                                            <p class="card-subtitle mb-2 text-muted text-center">{{ report.title }}</p>
                                            <div class="card-text text-center">
                                                <p>{{ report.synopsis }}</p>
                                            </div> <!-- card-text -->
                                        </div> <!-- card-body -->
                                    </div> <!-- card -->
                                {% endif %}
                            {% endfor %}
                        </div> <!-- card-deck -->
                </div> <!-- card-body -->
            </div> <!-- col-sm -->
        </div> <!-- row -->
    </div> <!-- container -->
{% endblock %}

reports/templates/reports/index.html
{% extends "base.html" %}

reports/templates/reports/po.html
{% extends "base.html" %}

{% block title %}PO{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm">
                <div class="card mb-3">
                    <div class="card-body">
                        <h1 class="card-title text-center">
                            {{ po.name }}
                        </h1> <!-- card-title -->
                    </div> <!-- card-body -->
                </div> <!-- card -->
            </div> <!-- col-sm -->
        </div> <!-- row -->
        <div class="row">
            <div class="col-sm">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            Created By:
                        </h5> <!-- card-title -->
                        <p class="card-text text-center">
                            {{ po.creator }}
                        </p>
                    </div> <!-- card-body -->
                </div> <!-- card -->
            </div> <!-- col-sm -->
            <div class="col-sm">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            Officers:
                        </h5> <!-- card-title -->
                        {% for officer in officers %}
                            <p class="card-text text-center">{{ officer }}</p>
                        {% endfor %}
                    </div> <!-- card-body -->
                </div> <!-- card -->
            </div> <!-- col-sm -->
            <div class="col-sm">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            Created On:
                        </h5> <!-- card-title -->
                        <p class="card-text text-center">
                            {{ po.created}}
                        </p>
                    </div> <!-- card-body -->
                </div> <!-- card -->
            </div> <!-- col-sm -->
        </div> <!-- row -->
        <div class="row">
            <div class="col-sm">
            </div> <!-- col-sm -->
            <div class="col-sm">
                <div class="card mt-3" style="width: 56em;">
                    <div class="card-body text-center">
                        <a href="{% url 'add_user' po.id %}" class="btn btn-dark mt-2 mb-2" role='button'>Add User</a>
                        <a href="{% url 'remove_user' po.id %}" class="btn btn-dark mt-2 mb-2" role='button'>Remove User</a>
                        <a href="{% url 'index' %}" class="btn btn-dark mt-2 mb-2" role='button'>Create Report</a>
                    </div> <!-- card-body -->
                </div> <!-- card -->
            </div> <!-- col-sm -->
            <div class="col-sm">
            </div> <!-- col-sm -->
        </div> <!-- row -->
    </div> <!-- container-fluid -->
{% endblock %}

reports/templates/reports/remove_user.html
{% extends "base.html" %}

{% block title %}Remove User{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm">
                <div class="<div class="card">
                    <div class="card-body bg-dark mt-3">
                        <h4 class="card-title text-center text-white bg-info">Remove user from {{ po.name }}</h4>
                            <form method="post">
                                {% csrf_token %}
                                <div class="card-text text-center text-white bg-light">
                                    {{ form.as_p }}
                                    <button class="btn bg-info text-white mb-2" type="submit">Remove User</button>
                                </div>
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}